name: check-quality
on:
  workflow_run:
    workflows: ["install-tools"]
    types:
      - completed
jobs:
  check-quality:
    runs-on:
      labels: [tart, macos]
    steps:
      - name: Run the quality check
        run: |
          ~/clone-repo-in-vm.sh https://$MACOS_CI_SETUP_TOKEN@github.com/SRGSSR/fake-and-temporary-pa-for-runners.git sonoma-fake-pillarbox
          cd ~/_repo
          make check-quality
