---
name: Continuous Integration
on: [push]
jobs:
  install-tools:
    name: "🪚 Tools installation"
    runs-on:
      labels: [tart, wk]
    steps:
      - uses: pkgxdev/setup@v1
        with:
          +: ffmpeg
