---
name: Continuous Integration
on: [push]
jobs:
  Check-quality:
    name: "🔎 Check quality"
    runs-on:
      labels: [tart, wk]
    steps:
      - uses: pkgxdev/setup@v1
        with:
          +: swiftlint shellcheck markdownlint yamllint
      - name: "Check quality"
        run: swiftlint --version
