---
name: Pull Request

on: [push]

jobs:
  check-quality:
    name: "🔎 Check quality"
    runs-on: tart
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the quality check
        run: make check-quality
