---
name: Pull Request

on: [push]

jobs:
  check-quality:
    name: "🔎 Check quality"
    runs-on: [macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the quality check
        run: make check-quality

  build-documentation:
    name: "📚 Build documentation"
    runs-on: [macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the documentation
        run: make doc

  tests:
    name: "🧪 Tests"
    runs-on: [macos-latest]
    strategy:
      matrix:
        platform: [ios, tvos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: ~/Packages
          key: ${{ runner.os }}-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-packages-

      - name: Run tests
        run: |
          make test-${{ matrix.platform }}
        env:
          HAS_PACKAGES_CACHE_HIT: |
            ${{ steps.packages-cache.outputs.cache-hit == 'true' }}

  archive-demos:
    name: "📦 Archives"
    runs-on: [macos-latest]
    strategy:
      matrix:
        platform: [ios, tvos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Apple certificate
        run: |
          Scripts/add-apple-certificate.sh \
          $RUNNER_TEMP \
          ${{ secrets.KEYCHAIN_PASSWORD }} \
          ${{ secrets.SRGSSR_APPLE_DEV_CERTIFICATE_B64 }}

      - name: Configure environment
        run: |
          Scripts/configure-environment.sh \
          ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }} \
          ${{ secrets.APPLE_ACCOUNT_INFO_B64 }}

      - name: Cache packages
        uses: actions/cache@v3
        id: packages-demo-cache
        with:
          path: ~/Demo/Packages
          key: ${{ runner.os }}-demo-packages-${{ hashFiles('Demo/**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-demo-packages-

      - name: Archive the demo
        run: |
          make archive-demo-${{ matrix.platform }}
        env:
          HAS_PACKAGES_CACHE_HIT: |
            ${{ steps.packages-demo-cache.outputs.cache-hit == 'true' }}
