---
name: Pull Request

on: [push]

jobs:
  check-quality:
    name: "🔎 Check quality"
    runs-on: tart
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the quality check
        run: make check-quality

  build-documentation:
    name: "📚 Build documentation"
    runs-on: tart
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the documentation
        run: make doc

  # tests:
  #   name: "🧪 Tests"
  #   runs-on: tart
  #   strategy:
  #     matrix:
  #       platform: [ios, tvos]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run tests
  #       run: make test-${{ matrix.platform }}
